version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

# Don't build any extra formats
formats: [] 